stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_PROJECT_NAME
  DOCKER_TAG: $CI_COMMIT_SHA
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_USERNAME: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

build-job:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
  artifacts:
    paths:
      - $DOCKER_IMAGE.tar

test-job:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load -i $DOCKER_IMAGE.tar
    - docker run -t $DOCKER_IMAGE /app/tests

deploy-job:
  stage: deploy
  script:
    - docker tag $DOCKER_IMAGE $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
  environment:
    name: production
    url: https://example.com
  only:
    - main

cleanup-job:
  stage: deploy
  script:
    - docker rmi $DOCKER_IMAGE
    - docker rmi $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
  when: always