name: CI / Docker

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build . --file Dockerfile -t awesomescripts