name: CI / Docker Build Image

on:
  schedule:
    - cron: '10 0 * * *'
  push:
    branches: [ "master", "*"]
  pull_request:
    branches: [ "master", "*" ]
  workflow_dispatch:

jobs:
  single-platform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image - Single Platform
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  multi-platform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Image for Platforms - macOS, Windows, Linux
      run: |
        docker buildx build --platform linux/amd64,windows/amd64,macos/amd64 -t awesomescripts:latest .
        echo "Complete."
